kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fb-direct-access
provisioner: pxd.portworx.com
parameters:
  backend: "pure_file"
  pure_export_rules: "*(rw)"
mountOptions:
  - nfsvers=3
  - tcp
allowVolumeExpansion: true
